### ISSUE TITLE
Test HDFS

### ISSUE THREAD

**Issue by cxinyi** [cxinyi/SEBC#12]

**Comment by cxinyi** [comment]
I have used the following code for teragen but there is only one file generated:

time hadoop jar /opt/cloudera/parcels/CDH/lib/hadoop-0.20-mapreduce/hadoop-examples.jar teragen -Dmapred.map.tasks=8 -D dfs.blocksize=64m -Dmapred.map.tasks.speculative.execution=false 51200000 tgen512m

**Comment by cxinyi** [comment]
The issue is solved. Just have to install YARN gateway to all the nodes.

**Comment by mfernest** [comment]
Incorrect content in `4_teragen.md`. Unfortunately, I cannot give you any credit for this work.

DNS
