### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by cxinyi** [cxinyi/SEBC#2]
I will be using Microsoft Azure for this lab,

**Comment by cxinyi** [comment]
Finished system configuration checks

**Comment by mfernest** [comment]
Please give the specifics of your environment, such as the instance types (name, CPU count, memory) and volume capacity.

**Comment by cxinyi** [comment]
![ds3_v2](https://cloud.githubusercontent.com/assets/23624579/20909636/d7a0df4e-bb97-11e6-8cdd-a541210bc111.PNG)

**Comment by cxinyi** [comment]
Installation completed

**Comment by mfernest** [comment]
`1_preinstall.md` - your step 3 show available space on the volume, not reserved space. Reserved space is a percentage of the volume that can be used by root for meta-operations.

Please fix this element of the lab and remove the `incomplete` flag when done.

**Comment by cxinyi** [comment]
Updated

**Comment by mfernest** [comment]
👍
